# Netlify configuration (опциональный способ деплоя)

[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"

[[plugins]]
  package = "@astrojs/netlify"

# Redirect rules
[[redirects]]
  from = "/admin/*"
  to = "/admin/:splat"
  status = 200

# Headers for security
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"

# CORS for feed.json
[[headers]]
  for = "/feed.json"
  [headers.values]
    Access-Control-Allow-Origin = "*"

# Cache static assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
