name: Deploy Blog to Server

on:
  push:
    branches: [main]
  pull_request:
    types: [closed]
    branches: [main]

jobs:
  deploy:
    # Запускаем только при пуше в main или при мерже PR
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.pull_request.merged == true)
    runs-on: ubuntu-latest
    
    steps:
      - name: Deploy to server via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: ${{ secrets.SERVER_PORT || 22 }}
          script: |
            echo "🚀 Starting blog deployment..."
            
            # Перейти в папку блога
            cd ~/aisender/sendogram-blog || exit 1
            
            # Подтянуть изменения из GitHub
            echo "📥 Pulling latest changes from GitHub..."
            git pull origin main
            
            # Вернуться в корень проекта
            cd ~/aisender
            
            # Пересобрать образ блога
            echo "🔨 Building Docker image..."
            docker-compose -f docker-compose.blog.yml build blog
            
            # Перезапустить контейнер
            echo "🔄 Restarting blog container..."
            docker-compose -f docker-compose.blog.yml up -d blog
            
            # Очистить старые образы
            echo "🧹 Cleaning up old images..."
            docker image prune -f
            
            # Проверить статус
            echo "✅ Deployment complete! Checking status..."
            docker-compose -f docker-compose.blog.yml ps | grep blog
            
            echo "🎉 Blog deployed successfully!"
